# Generated by Django 4.2.5 on 2023-11-07 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_created_by', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('region', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('committee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commettee_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commettee_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'committee',
            },
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'faq_category',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=45, null=True)),
                ('start_time', models.CharField(blank=True, max_length=45, null=True)),
                ('duration', models.CharField(blank=True, max_length=45, null=True)),
                ('end_time', models.CharField(blank=True, max_length=45, null=True)),
                ('expected_members', models.CharField(blank=True, max_length=45, null=True)),
                ('nature', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('link', models.CharField(blank=True, max_length=45, null=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.committee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('resolution_id', models.IntegerField(primary_key=True, serialize=False)),
                ('detail', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resolution_created_by', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.meeting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resolution_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resolution',
            },
        ),
        migrations.CreateModel(
            name='Workforce',
            fields=[
                ('workforce_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workforce_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workforce',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_updated_by', to=settings.AUTH_USER_MODEL)),
                ('workforce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.workforce')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('step_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='step_created_by', to=settings.AUTH_USER_MODEL)),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.resolution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='step_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'step',
            },
        ),
        migrations.CreateModel(
            name='Sla',
            fields=[
                ('sla_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sla_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sla_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sla',
            },
        ),
        migrations.CreateModel(
            name='Responsi',
            fields=[
                ('responsi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('responsi', models.CharField(blank=True, max_length=45, null=True)),
                ('channel', models.CharField(blank=True, max_length=45, null=True)),
                ('delivered', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsi_created_by', to=settings.AUTH_USER_MODEL)),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.resolution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsi_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'responsi',
            },
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('minute_id', models.IntegerField(primary_key=True, serialize=False)),
                ('minute', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='minute_created_by', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.meeting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='minute_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'minute',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Griever',
            fields=[
                ('griever_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(blank=True, max_length=255, null=True)),
                ('m_name', models.CharField(blank=True, max_length=255, null=True)),
                ('l_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=45, null=True)),
                ('age', models.CharField(blank=True, max_length=45, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=45, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('ward', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=45, null=True)),
                ('spouse', models.CharField(blank=True, max_length=255, null=True)),
                ('next_kin', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='griever_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='griever_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'griever',
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('grievance_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=45)),
                ('start_date', models.CharField(max_length=45)),
                ('end_date', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('what', models.CharField(blank=True, max_length=45, null=True)),
                ('where', models.CharField(blank=True, max_length=45, null=True)),
                ('who', models.CharField(blank=True, max_length=45, null=True)),
                ('result', models.CharField(blank=True, max_length=45, null=True)),
                ('comments', models.CharField(blank=True, max_length=45, null=True)),
                ('nature', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('operational_status', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('assignment_date', models.CharField(blank=True, max_length=255, null=True)),
                ('time_spent', models.CharField(blank=True, max_length=255, null=True)),
                ('last_pending_date', models.CharField(blank=True, max_length=255, null=True)),
                ('pending_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('resolution_date', models.CharField(blank=True, max_length=255, null=True)),
                ('conclusion', models.CharField(blank=True, max_length=255, null=True)),
                ('satisfaction_level', models.CharField(blank=True, max_length=255, null=True)),
                ('satisfaction_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('pending_started', models.CharField(blank=True, max_length=255, null=True)),
                ('pending_last_start', models.CharField(blank=True, max_length=255, null=True)),
                ('pending_stopped', models.CharField(blank=True, max_length=255, null=True)),
                ('pending_time_spent', models.CharField(blank=True, max_length=255, null=True)),
                ('anonymous', models.IntegerField(max_length=45)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.member')),
                ('child', models.ForeignKey(blank=True, db_column='child', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.grievance')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grievance_created_by', to=settings.AUTH_USER_MODEL)),
                ('griever', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.griever')),
                ('parent', models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grievance_grievance_parent_set', to='core.grievance')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='grievance_updated_by', to=settings.AUTH_USER_MODEL)),
                ('workforce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.workforce')),
            ],
            options={
                'db_table': 'grievance',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('faq_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('question', models.CharField(blank=True, max_length=45, null=True)),
                ('answer', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='faq_category', to='core.faqcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='faq_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='faq_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faq',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('path', models.CharField(blank=True, max_length=45, null=True)),
                ('format', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachment_created_by', to=settings.AUTH_USER_MODEL)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.grievance')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachment_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attachment',
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('agenda_id', models.IntegerField(primary_key=True, serialize=False)),
                ('agenda', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agenda_created_by', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.meeting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agenda_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agenda',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.IntegerField(primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, max_length=45, null=True)),
                ('responsible', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('start_date', models.CharField(blank=True, max_length=45, null=True)),
                ('end_date', models.CharField(blank=True, max_length=45, null=True)),
                ('action_status', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_created_by', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.step')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'action',
            },
        ),
        migrations.CreateModel(
            name='TeamHasMember',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.team')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.member')),
            ],
            options={
                'db_table': 'team_has_member',
                'unique_together': {('team', 'member')},
            },
        ),
        migrations.CreateModel(
            name='CommitteeHasMember',
            fields=[
                ('committee', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.committee')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.member')),
            ],
            options={
                'db_table': 'committee_has_member',
                'unique_together': {('committee', 'member')},
            },
        ),
    ]
