# Generated by Django 4.2.5 on 2023-11-07 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_client_id_alter_committee_committee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('severity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='severity_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='severity_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'severity',
            },
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('nature_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.CharField(blank=True, max_length=45, null=True)),
                ('updated_date', models.CharField(blank=True, max_length=45, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nature_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nature_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nature',
            },
        ),
    ]
