# Generated by Django 4.2.5 on 2023-11-15 09:36

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_severity_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='griever',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_to),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='griever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.griever'),
        ),
    ]
