# Generated by Django 4.2.5 on 2023-11-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_griever_profile_alter_grievance_griever'),
    ]

    operations = [
        migrations.AddField(
            model_name='griever',
            name='email',
            field=models.EmailField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='griever',
            name='postal_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
